# <DESCRIBE SERVICE>
service: wild-rydes-promo-discount

plugins:
  - serverless-python-requirements

custom:
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"
  profile: "${opt:aws-profile, env:AWS_PROFILE, env:AWS_DEFAULT_PROFILE, 'default'}"
  log_level: "${env:LOG_LEVEL, 'INFO'}"

  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  profile: ${self:custom.profile}
  stage: ${self:custom.stage}
  runtime: python3.6
  environment:
    LOG_LEVEL: ${self:custom.log_level}

functions:
  GetPromoDiscount:
    handler: handlers/get-promo-discount.handler
    description: "Return the promo discount value if there is one."
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: /promo
          method: post

resources:
  Outputs:
    WildRydesPromoDiscountInvokeUrl:
      Description: URL for the deployed wild rydes API
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - Ref: AWS::Region
            - ".amazonaws.com/${self:custom.stage}"
      Export:
        Name: "${self:service}-${self:provider.stage}-WildRydesPromoDiscountInvokeUrl"

    WildRydesGetPromoDiscountUrl:
      Description: URL for the deployed wild rydes API
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - Ref: AWS::Region
            - ".amazonaws.com/${self:custom.stage}/promo"
      Export:
        Name: "${self:service}-${self:provider.stage}-WildRydesGetPromoDiscountUrl"



